# Generated by Django 6.1.1 on 2026-10-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_esp', models.CharField(choices=[('ON', 'Включить'), ('OFF', 'Выключить')], max_length=10, verbose_name='Команда')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='время/дата')),
            ],
            options={
                'verbose_name': 'Команда LED',
                'verbose_name_plural': 'Команды LED',
            },
        ),
    ]
